[package]
name = "basic"
version = "0.1.0"
authors = ["Mike Tang <miketang84@outlook.com>"]

[dependencies]
sapper = { git="https://github.com/sappworks/sapper" }
#sapper = { path="../../../sapper" }
sapper_cookie = { path="../../" }
log = "0.3"
env_logger = "0.3"
